### ISSUE TITLE
missing docs on useConvexAuth hook

### ISSUE THREAD

**Issue by TripleSpeeder** [get-convex/convex-auth#143]
Is the `useConvexAuth` hook just not documented or should it not be used? Did not find it mentioned anywhere in convex auth docs.

**Comment by thomasballinger** [comment]
`useConvexAuth` is for any auth used with Convex and is imported from "convex/react", so it's documented at https://docs.convex.dev/auth/clerk#logged-in-and-logged-out-views

There's an unfortunate naming situation here: Convex the product supports using any authentication solution that provides a JWT identity token, and `useConvexAuth` is a reactive view of whether Convex considers the current connection authenticated. Convex Auth the library is one of these auth solutions.
