### ISSUE TITLE
Allow retrieving access token on the client

### ISSUE THREAD

**Issue by xixixao** [get-convex/convex-auth#23]
For use with HTTP actions (for example for HTTP streaming)

**Comment by SaidTayebi** [comment]
Is there a way to retrieve the access token at all ? I'd like to use the `googleapi` to list the authenticated user emails.

**Comment by xixixao** [comment]
This issue was fixed in 0932da870966e49b8b0ecdf50f42c015effa6611

**Comment by xixixao** [comment]
@SaidTayebi I assume you mean the access token from Google OAuth? You can pipe it via the profile to your user document, see https://labs.convex.dev/auth/config/oauth#retrieving-other-profile-information
