### ISSUE TITLE
Setup script should detect and run the project's package manager

### ISSUE THREAD

**Issue by itsMapleLeaf** [get-convex/convex-auth#26]
Currently, when running the auth setup tool in a [Bun](https://bun.sh) project, it tries to use npm:

![image](https://github.com/get-convex/convex-auth/assets/19603573/a22928fb-a198-4853-91d1-148c1ec48d77)

(This screenshot is only to illustrate running npm, I only got an error here because of my bad peer deps)

**Comment by xixixao** [comment]
@itsMapleLeaf can you say more about why this is a problem for you?

**Comment by itsMapleLeaf** [comment]
Sure, and I guess this isn't actually Bun-specific.

[Other generators nowadays detect which package manager your project uses and runs that.](https://github.com/withastro/astro/blob/88e2b43305c07ef8b489081a5a580584cbd7f342/packages/create-astro/src/actions/context.ts#L119) Otherwise, you have to wait for a (potentially _loooong_) install process via npm (which might even _fail_ due to strict peers, as seen above) before having to reinstall your deps again.

**Comment by xixixao** [comment]
@itsMapleLeaf that command doesn't install anything, so I don't think this is an issue right now. This would only be an issue if you only had `bunx` and not `npx` at all, but I think that's unlikely.

**Comment by itsMapleLeaf** [comment]
Huh, yeah it just runs `npx` and not `npm` 🫠 
I guess I'll just close this then, since `npx` failing in this case is a local issue.
