### ISSUE TITLE
Expose token on client for authenticating http actions

### ISSUE THREAD

**Issue by xixixao** [get-convex/convex-auth#38]
https://discord.com/channels/1019350475847499849/1263827486735732828

**Comment by hasanaktas** [comment]
@xixixao 
is there an estimated release date for this feature? We've moved to convex-auth and need to authorize our http endpoints.

**Comment by xixixao** [comment]
@hasanaktas tomorrow

**Comment by hasanaktas** [comment]
@xixixao 
I appreciate the Convex team's swift responsiveness.

Thank you.

**Comment by xixixao** [comment]
Fixed in 0932da8

**Comment by xixixao** [comment]
Fixed in 0932da8
