### ISSUE TITLE
Cannot find module `@convex-dev/auth/nextjs`

### ISSUE THREAD

**Issue by BorisZubchenko** [get-convex/convex-auth#46]
[Docs says](https://labs.convex.dev/auth/setup) to import `ConvexAuthNextJsProvider` from `@convex-dev/auth/nextjs`:
```tsx
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
```
However, `@convex-dev/auth/nextjs` doesn't seem to exist:
```
TS2307: Cannot find module @convex-dev/auth/nextjs or its corresponding type declarations.
```
![image](https://github.com/user-attachments/assets/cc34eaeb-5aad-41e6-b1af-9b8c68e8ada6)

**Comment by BorisZubchenko** [comment]
Corresponding Discord thread: https://discord.com/channels/1019350475847499849/1088161997662724167/threads/1269290047618940969

**Comment by xixixao** [comment]
Added the alpha installation instructions to Setup.
