### ISSUE TITLE
How to combine authTables with existing schema defined using convex-ents

### ISSUE THREAD

**Issue by shiftlabs1** [get-convex/convex-auth#47]
How do i combine the authTables schema exported from this library with existing schema in my project created using convex-ents (another convex library). I am already getting typescript error that i can not work around unless i specify one of this schema as "any" which i do not want to do , so as not to loose type inference

**Comment by xixixao** [comment]
Hey @shiftlabs1 , see https://labs.convex.dev/convex-ents/auth
