### ISSUE TITLE
Retrieve Google access_token and refresh_token 

### ISSUE THREAD

**Issue by SaidTayebi** [get-convex/convex-auth#51]
Hi, how can I get `access_token` and `refresh_token` from google provider ?

I need them to use the `googleapi` to list the authenticated user's emails.

**Comment by xixixao** [comment]
You can pipe it via the profile to your user document, see https://labs.convex.dev/auth/config/oauth#retrieving-other-profile-information

Reopen if needed.

**Comment by SaidTayebi** [comment]
Thnaks @xixixao for your reply ! I still can't make it work. The doc is kinda not clear and when I use `profile` from google, the user is not even created

**Comment by SaidTayebi** [comment]
Thanks ! Solves my issue !
