### ISSUE TITLE
Role base access control from middleware

### ISSUE THREAD

**Issue by rajatabcx** [get-convex/convex-auth#57]
I have different roles in my application and need to check them in the middleware file to manage the routing, i can only check the authentication state but no way of finding, role in middleware.

Also, need other user data in the middleware. Currently can't access it.

I have the role field in user table so they are related.

**Comment by xixixao** [comment]
@rajatabcx did you try authed `fetchQuery` from the middleware?

**Comment by rajatabcx** [comment]
Thank you, it worked, closing this
