### ISSUE TITLE
Not auto redirect after execute signOut function

### ISSUE THREAD

**Issue by tungnc3142** [get-convex/convex-auth#92]
My project use:

```
"@auth/core": "^0.35.3",
    "@convex-dev/auth": "^0.0.71",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-separator": "^1.1.0",
    "@radix-ui/react-slot": "^1.1.0",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "convex": "^1.16.3",
    "lucide-react": "^0.446.0",
    "next": "14.2.13",
    "react": "^18",
    "react-dom": "^18",
    "react-icons": "^5.3.0",
    "tailwind-merge": "^2.5.2",
    "tailwindcss-animate": "^1.0.7"
```

and this is my middleware

```
import {
  convexAuthNextjsMiddleware,
  createRouteMatcher,
  nextjsMiddlewareRedirect
} from '@convex-dev/auth/nextjs/server';

const isPublicPage = createRouteMatcher(['/auth']);

export default convexAuthNextjsMiddleware((request, { convexAuth }) => {
  if (!isPublicPage(request) && !convexAuth.isAuthenticated()) {
    return nextjsMiddlewareRedirect(request, '/auth');
  }
  if (isPublicPage(request) && convexAuth.isAuthenticated()) {
    return nextjsMiddlewareRedirect(request, '/');
  }
});

export const config = {
  // The following matcher runs middleware on all routes
  // except static assets.
  matcher: ['/((?!.*\\..*|_next).*)', '/', '/(api|trpc)(.*)']
};
```

When I execute signOut function from `useAuthActions` hooks the page not auto redirect to auth page but when i use signIn function they still auto redirect to home page
>

**Comment by kovigv** [comment]
Same problem

**Comment by kovigv** [comment]
Looks like you need to add some extra code. For example:

```typescript
import { useRouter } from "next/navigation";

const router = useRouter()

  const onPasswordSignIn = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setPending(true)
    signIn("password", {email, password, flow: "signIn"})
      .catch(() => {
        setError("Invalid email or password")
      })
      .finally(() => {
        setPending(false)
        router.push("/")
      })
  }
```

So router.push("/") will be a fix for that
You should add it on 
onPasswordSignIn
onPasswordSignUp
and on signOut
```typescript
"use client";

import { useAuthActions } from "@convex-dev/auth/react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";

export default function Home() {
  const { signOut } = useAuthActions();
  const router = useRouter()

  return (
    <div>
      Main Page
      <Button onClick={
        () => {signOut().then(() => {router.push("/auth")})}
      }>Sign Out</Button>
    </div>
  );
}
```

**Comment by tungnc3142** [comment]
> Looks like you @tungnc3142 need to add some extra code. For example:
> 
> ```ts
> import { useRouter } from "next/navigation";
> 
> const router = useRouter()
> 
>   const onPasswordSignIn = (e: React.FormEvent<HTMLFormElement>) => {
>     e.preventDefault()
>     setPending(true)
>     signIn("password", {email, password, flow: "signIn"})
>       .catch(() => {
>         setError("Invalid email or password")
>       })
>       .finally(() => {
>         setPending(false)
>         router.push("/")
>       })
>   }
> ```
> 
> So router.push("/") will be a fix for that You should add it on onPasswordSignIn onPasswordSignUp and on signOut
> 
> ```ts
> "use client";
> 
> import { useAuthActions } from "@convex-dev/auth/react";
> import { useRouter } from "next/navigation";
> import { Button } from "@/components/ui/button";
> 
> export default function Home() {
>   const { signOut } = useAuthActions();
>   const router = useRouter()
> 
>   return (
>     <div>
>       Main Page
>       <Button onClick={
>         () => {signOut().then(() => {router.push("/auth")})}
>       }>Sign Out</Button>
>     </div>
>   );
> }
> ```

Your help was greatly appreciated. Thank you!. But I just checked the document, and the signOut function is non-asynchronous

**Comment by TheanLim** [comment]
Seeing a similar error here -- doesn't work for Github and Google OAuth, but it works fine with custom signup (with password and email)

**Comment by tungnc3142** [comment]
> Seeing a similar error here -- doesn't work for Github and Google OAuth, but it works fine with custom signup (with password and email)

Have you tried with a lower version? I think the lower version of convex works fine

**Comment by kovigv** [comment]
> > Looks like you @tungnc3142 need to add some extra code. For example:
> > ```ts
> > import { useRouter } from "next/navigation";
> > 
> > const router = useRouter()
> > 
> >   const onPasswordSignIn = (e: React.FormEvent<HTMLFormElement>) => {
> >     e.preventDefault()
> >     setPending(true)
> >     signIn("password", {email, password, flow: "signIn"})
> >       .catch(() => {
> >         setError("Invalid email or password")
> >       })
> >       .finally(() => {
> >         setPending(false)
> >         router.push("/")
> >       })
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So router.push("/") will be a fix for that You should add it on onPasswordSignIn onPasswordSignUp and on signOut
> > ```ts
> > "use client";
> > 
> > import { useAuthActions } from "@convex-dev/auth/react";
> > import { useRouter } from "next/navigation";
> > import { Button } from "@/components/ui/button";
> > 
> > export default function Home() {
> >   const { signOut } = useAuthActions();
> >   const router = useRouter()
> > 
> >   return (
> >     <div>
> >       Main Page
> >       <Button onClick={
> >         () => {signOut().then(() => {router.push("/auth")})}
> >       }>Sign Out</Button>
> >     </div>
> >   );
> > }
> > ```
> 
> Your help was greatly appreciated. Thank you!. But I just checked the document, and the signOut function is non-asynchronous

Sorry
Maybe that would help
onClick={ async () => {
            await signOut();
            router.push("/auth");
          }}

**Comment by TheanLim** [comment]
>Have you tried with a lower version? I think the lower version of convex works fine

Do you mind sharing which version that worked for you? Thanks ahead!

**Comment by TheanLim** [comment]
> 
> ```ts
> onClick={ async () => {
>             await signOut();
>             router.push("/auth");
>           }}
> ```

Unfortunately it doesn't.  It must be something intricate with OAuth that's going on. 
I am seeing `POST /auth` in the log all these long (even before proposed solution), but the page is simply not getting directed.

**Comment by sshader** [comment]
👋 One of the library maintainers here -- the `signOut` action just signs you out and does not do any redirecting. Any redirecting needs to be handled by y'all since the exact behavior will vary from app to app (both the example with `.then` and the example with `await signOut()` look good).

For Next.js with SSA specifically, if you want to handle the redirect with middleware, I believe you'll want to trigger a reload after calling the `signOut` function (`router.reload` looks like the appropriate function from the Next docs)

**Comment by TheanLim** [comment]
It works! I ended up using `location.reload();`

```
onClick={async () => {
                        await signOut();
                        location.reload();
                    }}
````

Do you mind to share why we need a reload after signing out? As I mentioned before, this is only needed for Github and Google signIn method.
Thanks!

**Comment by demptd13** [comment]
But in my opinion, it is better to use a router because location.reload will only send to the authorization page after confirmation from the browser modal window by default.
And in the example below, we can customize the signOut function:

```ts
  const { signOut } = useAuthActions();
  const router = useRouter();

  const handleSignOut = async () => {
    await signOut();
    router.push("/auth");
  };

 return <Button onClick={handleSignOut}>Sign Out</Button>;
```

**Comment by xixixao** [comment]
Might be reasonable for the Next.js version to refresh the client side router cache automatically on sign out (similarly to sign in).

**Comment by xixixao** [comment]
I think this is a recent bug, because `npm create convex` Next.js's starter has the sign out button broken (it doesn't take the user back to the home page).

**Comment by xixixao** [comment]
Yup, this was changed/broken between 0.0.61 and 0.0.71. FYI @sshader
