### ISSUE TITLE
Apple auth client id and secret issue

### ISSUE THREAD

**Issue by rajangargsmartdata** [get-convex/convex-auth#93]
Hi Team,

Thank you for providing such a great library. I've implemented Apple authentication in my Expo project following the documentation. However, after completing all the steps, I encountered an issue where the Apple authentication was not working, and I received an "invalid client" error.

To ensure everything was set up correctly, I verified my credentials using the REST API, and they worked as expected. However, the issue persisted within the SDK.

Upon further investigation, I discovered that the `client_id` and `client_secret` were not being passed in the request made by the SDK. As a workaround, I patched the `authorizationCodeGrantRequest` method by adding the following lines:

```js
args[1].body.append("client_secret", client.client_secret);
args[1].body.append("client_id", client.client_id);
```

File: `@convex-dev/auth/dist/server/oauth.js`

After applying this patch, the issue was resolved, and Apple authentication started working as expected.

Please let me know if there’s anything I might have overlooked or if a more permanent fix is being considered.

**Comment by sshader** [comment]
Could you share more details about the error you were hitting (full error message, logs). Also can you confirm that the `Apple` `Auth.js` provider is instantiated with a `clientId` and `clientSecret`? [Example 1](https://github.com/nextauthjs/next-auth/blob/2d67f1177077ca0f5d8e2b02ebf3cb98c1d81972/packages/core/src/providers/apple.ts#L114) [Example 2](https://github.com/get-convex/convex-auth-example/blob/99845fcd0bf660f6aa1cfef4d4960424ac525033/convex/auth.ts#L17)

**Comment by rajangargsmartdata** [comment]
Hi @sshader , thanks for replying. I was setting the id and secret in convex dashboard only not in auth.js provider. I'll configure as you shared examples and will post here.

**Comment by rajangargsmartdata** [comment]
So I tried your examples here is what I found.

I tried before using clientId and clientSecret in auth provider file but it was not working.

I saw a new property `client` and tried adding the below code

``` client: {
        token_endpoint_auth_method: "client_secret_post",
      },```

Then it worked fine. 

Thanks.
